Add contents for `08 Basic App Porting`
unikraft/summer-of-code-2021 pull request #30
Opened 2021-08-28 15:36 UTC by nderjung

Signed-off-by: Alexander Jung <a.jung@lancs.ac.uk>

2021-08-29 13:50 UTC, CristiBM reviewed
I've gone through the session contents and tried out the tutorials; very nice work :) I've left just some minor comments. Should be ok after addressing these.

2021-08-29 13:50 UTC, CristiBM commented on content/en/docs/sessions/08-basic-app-porting/index.md
> +unikernels.
```suggestion
in this section.  Note that providing patches is an unfortunate workaround to
the inherent differences between Linux userspace applications and libraries and
unikernels.
```

2021-08-29 13:50 UTC, CristiBM commented on content/en/docs/sessions/08-basic-app-porting/index.md
> +first princples"
```suggestion
first principles"
```

2021-08-29 13:50 UTC, CristiBM commented on content/en/docs/sessions/08-basic-app-porting/index.md
> +A shared library called [`libfortune`](https://github.com/nderjung/libfortune)
Link https://github.com/nderjung/libfortune does not (yet?) seem to point to a valid repo. Maybe it's private?

2021-08-29 15:39 UTC, nderjung commented on content/en/docs/sessions/08-basic-app-porting/index.md
> +interpreted, you do not need to follow this tutorial.  Instead, simply mount the
I see what you mean.  My point is:

  * If you are wishing to run a HLL on Unikraft which is already supported, e.g. the reader wishes to "port a simple application written in python" (for example) then this is the wrong tutorial for the reader;
  * If you are wishing to port a new HLL interpreter to Unikraft, for example PHP, then this tutorial is for you.
  
  I'll update the text accordingly.

2021-08-29 15:43 UTC, nderjung commented on content/en/docs/sessions/08-basic-app-porting/index.md
> +      iperf3
Yes, you have access to an internal version of iperf3 so this will only apply to you and other contrbutors to Unikraft who can see this internal `lib-iperf3`: so it fails for me too.  The solve for you is to simply update your `.kraftrc` with only 1 `list.origins`, and that's the Unikraft core repo and then start this process of the tutorial.

```toml
[list]
origins = [
  "http://github.com/unikraft/unikraft.git",
]
```

2021-08-29 15:43 UTC, nderjung commented on content/en/docs/sessions/08-basic-app-porting/index.md
> +A shared library called [`libfortune`](https://github.com/nderjung/libfortune)
I need to make it public :)

2021-08-29 15:44 UTC, nderjung commented
Thanks for the feedback @CristiBM :)  I'll do an update with your suggested changes.

2021-08-29 18:24 UTC, craciunoiuc requested changes
Hey Alex,

Here is everything I found regarding the session. They are mostly typos and misplaced/missing commas.

Great work!

Cezar

2021-08-29 18:24 UTC, craciunoiuc commented on content/en/docs/sessions/08-basic-app-porting/index.md
> +      changes to it in a non-standard way.
```suggestion
    * Running scripts which generate new source files from templates;
    * Compiling files preemptively before Unikraft starts `build`ing source
      files
    * Checking for additional tools or building additional tools which are
      required to build the library
    * Advanced patching techniques to the source files of the library which make
      changes to it in a non-standard way
```

2021-08-29 18:24 UTC, craciunoiuc commented on content/en/docs/sessions/08-basic-app-porting/index.md
> +porting "from first principles," including addressing all the steps in the
```suggestion
porting "from first principles", including addressing all the steps in the
```

2021-08-29 18:24 UTC, craciunoiuc commented on content/en/docs/sessions/08-basic-app-porting/index.md
> +context of the "unikernel model," that is, single-purpose OSes with a single
```suggestion
context of the "unikernel model", that is, single-purpose OSes with a single
```

2021-08-29 18:24 UTC, craciunoiuc commented on content/en/docs/sessions/08-basic-app-porting/index.md
> + * That all features are necessary.
```suggestion
 * That all syscalls are available (which is not the case for Unikraft, although
   there is significant work being done to bring more syscalls to Unikraft)
 * That the filesystem is complete
 * That the P in POSIX is _not_ silent: Unfortunately it is and *unix-type systems
   do not always adhere to standards and make their own assumptions.  For
   example, oftentimes there are differences between Linux and BSD-type OSes
   which need to be accounted for
 * That all features are necessary
```

2021-08-29 18:24 UTC, craciunoiuc commented on content/en/docs/sessions/08-basic-app-porting/index.md
> +   approach.)
```suggestion
   approach)
```

2021-08-29 18:24 UTC, craciunoiuc commented on content/en/docs/sessions/08-basic-app-porting/index.md
> +environment.  But the unfortunate truth is that "bitshifts happen," and we
```suggestion
environment.  But the unfortunate truth is that "bitshifts happen", and we
```

2021-08-29 18:24 UTC, craciunoiuc commented on content/en/docs/sessions/08-basic-app-porting/index.md
> +| Order | Level | Regitraring method                  | Type   |
```suggestion
| Order | Level | Registering method                  | Type   |
```

2021-08-29 18:24 UTC, craciunoiuc commented on content/en/docs/sessions/08-basic-app-porting/index.md
> +There is a well-known kerel quote, which should be introduced to this library as
```suggestion
There is a well-known kernel quote, which should be introduced to this library as
```

2021-08-29 18:36 UTC, craciunoiuc commented on content/en/docs/sessions/08-basic-app-porting/index.md
> +used with unikernels.
The task to give feedback is missing!

2021-08-31 07:51 UTC, nderjung commented on content/en/docs/sessions/08-basic-app-porting/index.md
> +unikernels.
The "are" is correct, "patches" is plural. :)

2021-08-31 07:53 UTC, nderjung commented on content/en/docs/sessions/08-basic-app-porting/index.md
> +
Oh no! I am a big fan of `;` :D

2021-08-31 08:09 UTC, nderjung commented
Hey @CristiBM and @craciunoiuc,

Thanks so much for the feedback and comments -- I really appreciate it!

I've just force-pushed with (most) of your suggested changes!  The only thing I didn't change (sorry Cezar!) is the semi-colon lists 😉

I've added `Reviewed-by` tags for you both, so if I get the go-ahead from you, we can just "smash that merge button" :)

I just need to upstream the `libfortune` and make the repo public, I will be able to do that later this evening :)

2021-08-31 08:15 UTC, craciunoiuc commented
> 
> 
> Hey @CristiBM and @craciunoiuc,
> 
> Thanks so much for the feedback and comments -- I really appreciate it!
> 
> I've just force-pushed with (most) of your suggested changes! The only thing I didn't change (sorry Cezar!) is the semi-colon lists and commas within quotes 😉
> 
> I've added `Reviewed-by` tags for you both, so if I get the go-ahead from you, we can just "smash that merge button" :)
> 
> I just need to upstream the `libfortune` and make the repo public, I will be able to do that later this evening :)

Hey @nderjung,

All good from me, you are free to "like, comment, subscribe" the merge button 🥇.

2021-08-31 12:13 UTC, CristiBM commented
> Hey @CristiBM and @craciunoiuc,
> 
> Thanks so much for the feedback and comments -- I really appreciate it!
> 
> I've just force-pushed with (most) of your suggested changes! The only thing I didn't change (sorry Cezar!) is the semi-colon lists and commas within quotes wink
> 
> I've added `Reviewed-by` tags for you both, so if I get the go-ahead from you, we can just "smash that merge button" :)
> 
> I just need to upstream the `libfortune` and make the repo public, I will be able to do that later this evening :)

All good from me too

2021-08-31 12:32 UTC, craciunoiuc reviewed
Hey @nderjung,

Two more comments on the new part. Please look over them.

Cezar

2021-08-31 12:32 UTC, craciunoiuc commented on content/en/docs/sessions/08-basic-app-porting/index.md
> +All applications must follow the following standard prototype for `main`:
```suggestion
All applications must implement the following standard prototype for `main`:
```

"follow the following" doesn't sound that good

2021-08-31 12:32 UTC, craciunoiuc commented on content/en/docs/sessions/08-basic-app-porting/index.md
> +   ifneq($(CONFIG_LIBIPERF3_MAIN_FUNCTION),y)
```suggestion
   ifdef CONFIG_LIBIPERF3_MAIN_FUNCTION
```

I think it also works like this, whatever you prefer.

2021-08-31 12:35 UTC, nderjung commented on content/en/docs/sessions/08-basic-app-porting/index.md
> +   ifneq($(CONFIG_LIBIPERF3_MAIN_FUNCTION),y)
I have not seen this syntax for make before

2021-09-01 07:13 UTC, craciunoiuc commented on content/en/docs/sessions/08-basic-app-porting/index.md
> +   ifneq($(CONFIG_LIBIPERF3_MAIN_FUNCTION),y)
I used it a bit when porting p11-kit. Here is an example[1]:

[1] https://www.gnu.org/software/make/manual/html_node/Conditional-Syntax.html

2021-09-01 12:35 UTC, nderjung commented on content/en/docs/sessions/08-basic-app-porting/index.md
> +   ifneq($(CONFIG_LIBIPERF3_MAIN_FUNCTION),y)
In this case, we want it to not equal `y`.  When providing main, in this case, we do not want to rewrite the method.

2021-09-01 13:53 UTC, razvand approved these changes
All OK.

2021-09-01 13:54 UTC, merged