Add session 02 content
unikraft/summer-of-code-2021 pull request #5
Opened 2021-08-17 19:19 UTC by cristian-vijelie

I have seen that Sergiu also has some work items with 9pfs. I'm not sure if I should replace mine with something else, reduce its size, or leave it as it is.

2021-08-19 05:56 UTC, razvand commented
@cristian-vijelie , do leave 9pfs as part of session 02. Even if it's in session 01, repetitio mater studiorum est.

2021-08-20 14:36 UTC, razvand requested changes
Make work items more explicit. Add solutions. Turn more exercises / challenges in tutorials.

2021-08-20 14:36 UTC, razvand commented on content/en/docs/sessions/02-behind-scenes/index.md
> +Spot the differences between what is required for the 2 platforms.
As part of the solution folder, give some pointers of what you are supposed to see.

2021-08-20 14:36 UTC, razvand commented on content/en/docs/sessions/02-behind-scenes/index.md
> +Build the core Unikraft image for the **linuxu** and **KVM** platforms, and run them.
This is rather unspecific. You need an application to build that.

At the same time, they need some reminders. I would provide them, as a tutorial, **all** steps required to build [app-helloworld](https://github.com/unikraft/app-helloworld) using kraft and make. Make sure there won't be any path related issues in `Makefile` (or they would be using the `UK_...` environment variables). You can copy/adapt from [Session 01: Baby Steps](https://usoc21.unikraft.org/docs/sessions/01-baby-steps/).

2021-08-20 14:36 UTC, razvand commented on content/en/docs/sessions/02-behind-scenes/index.md
> +Build the core Unikraft image for the KVM platform, for the **ARM** and **x86** architectures, and run them.
They don't have an idea on how to run for **ARM**. I would let them know, as a tutorial. With all instructions and step by step details.

2021-08-20 14:36 UTC, razvand commented on content/en/docs/sessions/02-behind-scenes/index.md
> +Enable the internal debugging library for Unikraft (`ukdebug`), and make it display messages up to debug level.
I would once again make this a tutorial. Then, as "tasks":
* tell participants to update the configuration for the log-level
* tell participants to add some debug messages in the `main.c` file

2021-08-20 14:36 UTC, razvand commented on content/en/docs/sessions/02-behind-scenes/index.md
> +Run the Unikraft core image, for KVM platform, x86 architecture, and measure the runtime, first without using KVM hardware acceleration, then while using it.
They don't know how to measure. I would provide them a script:
```
\time -v sudo ...
```
or
```
sudo perf stat ...
```

2021-08-20 14:36 UTC, razvand commented on content/en/docs/sessions/02-behind-scenes/index.md
> +Run the [helloworld app](https://github.com/unikraft/app-helloworld), using kraft.
This should be moved at the very beginning as a reminder of building (with `kraft` and `make`) from the first session.

2021-08-20 14:36 UTC, razvand commented on content/en/docs/sessions/02-behind-scenes/index.md
> +For this tutorial, the aim is to modify the helloworld app, to use the 9pfs filesystem: read something from a file, and display it.
I added this phrase. Always start a section by saying what needs to happen as part of it. Start with why, start with the goal, the aim.

2021-08-20 14:36 UTC, razvand commented on content/en/docs/sessions/02-behind-scenes/index.md
> +TODO: the archive - I don't know if it's needed to be an archive; it doesn't run either way
So this doesn't work? It's unclear from your wording.

2021-08-20 14:36 UTC, razvand commented on content/en/docs/sessions/02-behind-scenes/index.md
> +### 07. Tutorial: Adding Filesystems to an Application
Add the entire configuration / resulting files in the `sol/` subfolder (see [session 01](https://github.com/unikraft/summer-of-code-2021/tree/main/content/en/docs/sessions/01-baby-steps/sol)), such that, in the likely case they will run into issues, they will have a reference solution.

2021-08-20 14:36 UTC, razvand commented on content/en/docs/sessions/02-behind-scenes/index.md
> +Modify **Config.uk**, for the helloworld app, so that the user can choose if the app will display *Hello world*, or what it reads from the file from the previous exercise.
Make it a tutorial, it's not trivial.

2021-08-20 14:36 UTC, razvand commented on content/en/docs/sessions/02-behind-scenes/index.md
> +### 09. Arguments from Command Line
Again, make it a tutorial.

2021-08-20 14:36 UTC, razvand commented on content/en/docs/sessions/02-behind-scenes/index.md
> +Delete `Config.uk` and reconfigure / rebuild the app.
This is unclear to me. What is the aim? What should they notice?

2021-08-20 14:36 UTC, razvand commented on content/en/docs/sessions/02-behind-scenes/index.md
> +Once configured, the Unikraft image can be built, using make, and run, using the appropriate method (Linux ELF loader, qemu-kvm, xen, others).
Insist that there are three ways of configuring an application:
* defining a `Config.uk` file for it with the corresponding options enabled `select CONFIG_FOOBAR`; then run `make menuconfig`, save and that's it (I don't know of an option to do this non-interactively)
* defining a `kraft.yaml` file, adding the configuration options and then running `kraft config`
* using `make menuconfig` and interactively selecting options then saving

Everything results in `.config` being generated, that will be then used by `make` or `kraft build`.

2021-08-20 14:38 UTC, razvand commented on content/en/docs/sessions/02-behind-scenes/index.md
> +Once configured, the Unikraft image can be built, using make, and run, using the appropriate method (Linux ELF loader, qemu-kvm, xen, others).
And add a tutorial for a simple app (helloworld style) where they configure using all three options. And then throughout the sessions, they do tutorials / challenges using any / all of these options.

2021-08-20 14:43 UTC, cristian-vijelie commented on content/en/docs/sessions/02-behind-scenes/index.md
> +TODO: the archive - I don't know if it's needed to be an archive; it doesn't run either way
No, it doesn't work. Without rebuilding, I can run it with `qemu-guest`, but not with `kraft run`. My guess is that the mount tag used by kraft is not `fs0`, but `kraft run -D` doesn't display anything, so I can't see the command used

2021-08-20 14:44 UTC, cristian-vijelie commented on content/en/docs/sessions/02-behind-scenes/index.md
> +Delete `Config.uk` and reconfigure / rebuild the app.
That the things they added don't happen anymore. I'm not sure, either, about this item.

2021-08-20 14:59 UTC, razvanvirtan commented on content/en/docs/sessions/02-behind-scenes/index.md
> +Virtual machines represent an abstraction of the hardware, over which an operating system can run, thinking that it is alone on the system, and that it controls the hardware below it.
```suggestion
Virtual machines represent an abstraction of the hardware, over which an operating system can run, thinking that it is alone on the system and that it controls the hardware below it.
```

2021-08-20 14:59 UTC, razvanvirtan commented on content/en/docs/sessions/02-behind-scenes/index.md
> +* The **Type 1 hypervisor**, also known as as **bare-metal hypervisor**, has direct access to the hardware, and controls all the operating systems that are running on the system.
```suggestion
* The **Type 1 hypervisor**, also known as as **bare-metal hypervisor**, has direct access to the hardware and controls all the operating systems that are running on the system.
```

2021-08-20 14:59 UTC, razvanvirtan commented on content/en/docs/sessions/02-behind-scenes/index.md
> +When Unikraft is running using QEMU/KVM, it can either be run on an emulated system, or a (para)virtualized one.
```suggestion
When Unikraft is running using QEMU/KVM, it can either be run on an emulated system or a (para)virtualized one.
```

2021-08-20 14:59 UTC, razvanvirtan commented on content/en/docs/sessions/02-behind-scenes/index.md
> +  [Lwip](https://github.com/unikraft/lib-lwip) is an external library, that defines networking protocols, like IP, TCP, UDP.
```suggestion
  [Lwip](https://github.com/unikraft/lib-lwip) is an external library that defines networking protocols, like IP, TCP, UDP.
```

2021-08-20 14:59 UTC, razvanvirtan commented on content/en/docs/sessions/02-behind-scenes/index.md
> +Those symbols are usable both in the C code, to include certain functionalities only if they were selected in the configuring process, and in the actual building process, to include/ exclude source f
```suggestion
Those symbols are usable both in the C code, to include certain functionalities only if they were selected in the configuring process, and in the actual building process, to include / exclude source files, or whole libraries.
```

2021-08-20 14:59 UTC, razvanvirtan commented on content/en/docs/sessions/02-behind-scenes/index.md
> +* This configuration is made possible by a system based on Kconfig, that uses **Config.uk** files to add possible configurations, and **.config** files to store the configuration for the build.
```suggestion
* This configuration is made possible by a system based on Kconfig, that uses **Config.uk** files to add possible configurations, and **.config** files to store the specific configuration for a build.
```

2021-08-20 14:59 UTC, razvanvirtan commented on content/en/docs/sessions/02-behind-scenes/index.md
> +* The configuration step creates symbols, taht are visible in both Makefiles and source code.
```suggestion
* The configuration step creates symbols, that are visible in both Makefiles and source code.
```

2021-08-20 14:59 UTC, razvanvirtan commented on content/en/docs/sessions/02-behind-scenes/index.md
> +* Unikraft has an internal libc, but it can use other, more complex and complete, libcs, like newlib and musl.
```suggestion
* Unikraft has an internal libc, but it can use others, more complex and complete,  like newlib and musl.
```

2021-08-20 14:59 UTC, razvanvirtan commented on content/en/docs/sessions/02-behind-scenes/index.md
> +Build the core Unikraft image for the **linuxu** and **KVM** platforms, and run them.
```suggestion
Build the core Unikraft images for the **linuxu** and **KVM** platforms, and run them.
```

2021-08-20 14:59 UTC, razvanvirtan commented on content/en/docs/sessions/02-behind-scenes/index.md
> +
```suggestion
For building, use the manual Makefile based method presented in Session 1.

```

2021-08-20 14:59 UTC, razvanvirtan commented on content/en/docs/sessions/02-behind-scenes/index.md
> +
```suggestion
When running the ARM image using **qemu-system**, you may observe that it gets stuck.
Set a specific `machine` type and `cpu`, using the qemu-system options.
In order to view the available machine types for your version of qemu, run `qemu-system-aarch64 -machine help` (same for cpu, after choosing the machine).
In order to avoid problems, we recommend using the `virt` machine type,
```

2021-08-20 14:59 UTC, razvanvirtan commented on content/en/docs/sessions/02-behind-scenes/index.md
> +
I've run into this several times and I think it would be worth it to warn the participants. Also, it is a good place to make them dig a little bit into qemu options and build a command.
However, not all machines and cpus are compatible with running the images ( `-machine virt -cpu cortex-a57` should always work). Alternatively, we can give them the command directly.

2021-08-20 14:59 UTC, razvanvirtan commented on content/en/docs/sessions/02-behind-scenes/index.md
> +Enable the internal debugging library for Unikraft (`ukdebug`), and make it display messages up to debug level.
```suggestion
Enable the internal debugging library for Unikraft (`ukdebug`) and make it display messages up to debug level.
```

2021-08-20 14:59 UTC, razvanvirtan commented on content/en/docs/sessions/02-behind-scenes/index.md
> +For this tutorial, the aim is to modify the helloworld app, to use the 9pfs filesystem: read something from a file, and display it.
I think the participants may run into a unikraft version issue at this task. Starting from the helloworld application built at task 06, they could try using `~/.unikraft/unikraft` as the core repo for this task too. This will cause linking errors when adding newlib and building the image using `make`, because the unikraft version pulled by kraft is too old (we basically need `staging)`.
A solution to this situation would be to ask them use a fresh clone of the unikraft repo, set on the USoC branch. This may also be required for the 9pfs task in session 1, since using the USoC branch is never mentioned in the session text.

2021-08-20 14:59 UTC, razvanvirtan commented on content/en/docs/sessions/02-behind-scenes/index.md
> +Enable **nolibc**, and then, as a separate config / build, **newlibc**, both by using **make menuconfig** and modifying **kraft.yaml**.
```suggestion
Enable **nolibc** and then, as a separate config / build, **newlibc**, both by using **make menuconfig** and modifying **kraft.yaml**.
```

2021-08-20 14:59 UTC, razvanvirtan commented on content/en/docs/sessions/02-behind-scenes/index.md
> +Make sure than after this change, the application can still be built and run.
```suggestion
Make sure that after this change, the application can still be built and run.
```

2021-08-20 15:03 UTC, cristian-vijelie commented on content/en/docs/sessions/02-behind-scenes/_index.md
> +
Yes, there will be kraft commands from session 01

2021-08-20 15:11 UTC, cristian-vijelie commented on content/en/docs/sessions/02-behind-scenes/_index.md
> +Modify the helloworld app, to use the 9pfs filesystem: read something from a file, and display it.
I know there's a problem. When doing the kraft part, in kraft.yaml I specified that the version for both newlib and unikraft should be `staging`. I'll make it clearer.

2021-08-21 00:44 UTC, ungps requested changes
I left a couple of suggestions. I agree with Razvan that it should be more "introductory" and have some more tutorials. We don't want to scare anybody.

2021-08-21 00:44 UTC, ungps commented on content/en/docs/sessions/02-behind-scenes/index.md
> +See what components are initialized in `setup.c`, in both cases.
I would give some pointers, such as:

As we can see, the Linuxu version ([plat/linuxu/setup.c](https://github.com/unikraft/unikraft/blob/staging/plat/linuxu/setup.c)) just does a couple of initializations. The kvm version ([plat/kvm/x86/setup.c](https://github.com/unikraft/unikraft/blob/staging/plat/kvm/x86/setup.c)) is more complex, but don't worry, it just does a couple of more initializations. Just take a look at the end of the file, at `_libkvmplat_entry()`, ignore the rest of the file.

--

The kvm file is way too complex for someone such early in the os dev journey to understand imo.

Since this is still an intro into unikraft, we should have a couple of tutorials. The most of participants are probably far away from being independent. Maybe continue with something way easier to understand. Something like:

Shortly, either if we're running on KVM or linuxu, we will reach the same point: booting Unikraft (which is done by calling `ukplat_entry(...);` / `ukplat_entry_argp(...)` in `setup.c` file we've talked about before). Let's take a look now at [lib/ukboot/boot.c](https://github.com/unikraft/unikraft/blob/staging//lib/ukboot/boot.c). This is where these two functions are defined. Let's inspect what `ukplat_entry()` does and focus on just a couple of `if`/`ifdef` guarded blocks:
* In `#if CONFIG_LIBUKALLOC` block, the memory allocator is declared, but it will actually be initialized later in the same function
* in `#if CONFIG_LIBUKSCHED` block, the scheduler is declared, but it will actually be initialized later in the same function
* in `#ifdef CONFIG_LIBUKLIBPARAM` block, we will call a unikraft core library function:  `uk_libparam_parse()`. This will parse command line arguments given to the kernel and pass them further to the libraries.
* in the following couple of (`if` / `elif`) blocks, we try to initialize the allocator declared before. Let's not worry about this for now.
* there will be another `#if CONFIG_LIBUKALLOC` block, but in this one, we initialize the interrupt request (IRQ) subsystem. The IRQ subsystem is necessary to communicate with devices (for example with the network device)
* there will be two `#if CONFIG_LIBUKSCHED` block, but in these ones, the scheduler declared before gets initialized and started.
* in the end, we will just call `main_thread_func(&tma);` which will at some point (not too further away) start our application, but that's a story for another time.

2021-08-22 09:29 UTC, cristian-vijelie commented on content/en/docs/sessions/02-behind-scenes/index.md
> +Once configured, the Unikraft image can be built, using make, and run, using the appropriate method (Linux ELF loader, qemu-kvm, xen, others).
I would leave out the first option from tutorials / work items, for now.

2021-08-22 10:55 UTC, razvanvirtan commented on content/en/docs/sessions/02-behind-scenes/index.md
> +To send an argument while using kraft, we use the `-a` option, like this:
```suggestion
To send an argument while using kraft:
```

2021-08-22 12:41 UTC, cristian-vijelie commented on content/en/docs/sessions/02-behind-scenes/index.md
> +See what components are initialized in `setup.c`, in both cases.
I would rather let them inspect the code themselves and come with questions. I don't want to put too much emphasize on what happens there. They should just find where certain components are initialized, with the aid of the output from ukdebug

2021-08-23 16:46 UTC, razvanvirtan commented on content/en/docs/sessions/02-behind-scenes/index.md
> +TODO: the archive - I don't know if it's needed to be an archive; it doesn't run either way
I think one way to go is using kraft for building and  `qemu-guest` for running (at least they will learn how to use `kraft.yaml` to configure an application) .

2021-08-23 16:46 UTC, razvanvirtan commented on content/en/docs/sessions/02-behind-scenes/index.md
> +Delete `Config.uk` and reconfigure / rebuild the app.
They could also see that all the applications specific options are removed from the configuration menu.

2021-08-24 08:52 UTC, razvanvirtan commented on content/en/docs/sessions/02-behind-scenes/sol/04-going-through-the-code/README.txt
> +are parsed, to see if any of those arguments are destined to a library,
```suggestion
are parsed to see if any of those arguments are destined to a library,
```

2021-08-24 08:52 UTC, razvanvirtan commented on content/en/docs/sessions/02-behind-scenes/sol/04-going-through-the-code/README.txt
> +interrupts are enable, the clock is set up, and the main function, from
```suggestion
interrupts are enabled the clock is set up, and the main function, from
```

2021-08-24 08:52 UTC, razvanvirtan commented on content/en/docs/sessions/02-behind-scenes/sol/11-less-power/README.txt
> +An easy execrise to finish the day :)
```suggestion
An easy exercise to finish the day :)
```

2021-08-24 08:52 UTC, razvanvirtan commented on content/en/docs/sessions/02-behind-scenes/sol/10-more-power/main.c
> +#include "mysort.h"
I think you could also add define guards to this include.

2021-08-24 14:04 UTC, razvand approved these changes
All good.

2021-08-24 14:04 UTC, merged