Add session contents for `07: Binary compatibility and syscall shim`
unikraft/summer-of-code-2021 pull request #6
Opened 2021-08-18 13:29 UTC by danield20

2021-08-18 19:26 UTC, razvand requested changes
Please write each phrase on a separate line.

Please Use Capitalized Words for Titles.

I'll be back with a more in-depth review, likely as a separate commit.

2021-08-21 12:23 UTC, mogasergiu commented on content/en/docs/sessions/07-syscall-shim/index.md
> +As stated previously the system call shim layer is the layer that we use in order to achieve the same system call behaviour as the Linux kernel.
```suggestion
As stated previously, the system call shim layer is what we use in order to achieve the same system call behaviour as the Linux kernel.
 ```

2021-08-21 12:27 UTC, mogasergiu commented on content/en/docs/sessions/07-syscall-shim/index.md
> +![Libraries configuration](images/config-image)
Maybe it would be a good idea to also show the sub-option of enabling `libc stubs` from `syscall-shim` so that they know that sometimes this is not enabled by default.

2021-08-21 12:27 UTC, mogasergiu commented on content/en/docs/sessions/07-syscall-shim/index.md
> +Now that we saw how we can run an executable on top of Unikraft though binary compatibility, let's take a look at what happens behind the scenes.
```suggestion
Now that we saw how we can run an executable on top of Unikraft through binary compatibility, let's take a look at what happens behind the scenes.
 ```

2021-08-21 12:27 UTC, mogasergiu commented on content/en/docs/sessions/07-syscall-shim/index.md
> +Hint 1: http://docs.unikraft.org/developers-app.html#syscall-shim-layer
```suggestion
**Hint 1**: [Syscall Shim Layer](http://docs.unikraft.org/developers-app.html#syscall-shim-layer)
 ```

2021-08-21 12:27 UTC, mogasergiu commented on content/en/docs/sessions/07-syscall-shim/index.md
> +Hint 2: check the `brk.c`, `Makefile.uk` and `exportsyms.uk` file in the app-elfloader directory.
```suggestion
**Hint 2**: Check the `brk.c`, `Makefile.uk` and `exportsyms.uk` files in the `app-elfloader` directory.
 ```

2021-08-21 12:28 UTC, mogasergiu commented on content/en/docs/sessions/07-syscall-shim/index.md
> +https://dtrugman.medium.com/elf-loaders-libraries-and-executables-on-linux-e5cfce318f94
```suggestion
[Elf Loaders, Libraries and Executables on Linux](https://dtrugman.medium.com/elf-loaders-libraries-and-executables-on-linux-e5cfce318f94)
```

2021-08-24 14:43 UTC, dragosargint commented on content/en/docs/sessions/07-syscall-shim/index.md
> +
A suggestion of one additional task: we can take the source code from task 4 and compile it directly for Unikraft. They should define a system call, (we can keep the getcpu syscall) with UK_SYSCALL_R_DEFINE and UK_LLSYSCALL_R_DEFINE macros and inspect the program flow using gdb. They may even make some time measurements: defining the libc wrapper from the shim layer vs using the syscall instruction.

2021-08-24 14:58 UTC, danield20 commented on content/en/docs/sessions/07-syscall-shim/index.md
> +* **gcc version at least 8.4.0**
Did you try with gcc-8 and it worked?

2021-08-24 15:02 UTC, danield20 commented on content/en/docs/sessions/07-syscall-shim/index.md
> +student:~/apps/app-elfloader$ cp demo/01/config .config
I am not sure about this as the scope of the session is to see how the syscall shim and the binary compat layer work. @razvand  what do you think?

2021-08-24 15:27 UTC, dragosargint commented on content/en/docs/sessions/07-syscall-shim/index.md
> +* **gcc version at least 8.4.0**
Yes, with gcc 8.4.0 it works.

2021-08-25 07:26 UTC, razvand commented on content/en/docs/sessions/07-syscall-shim/index.md
> +student:~/apps/app-elfloader$ cp demo/01/config .config
I'm mostly favoring them do the configuration. It's very good to reiterate on this and learn by repeating configuration steps. So I'd go for @dragosargint 's proposal.

However, if the configuration is too complicated, we can just tell them to copy the `.config` file. In any case, the `.config` file will be available in the solution, just as @dragosargint proposed.

2021-08-30 23:54 UTC, razvand commented on content/en/docs/sessions/07-syscall-shim/index.md
> +There are two definition macros that we can use in order to add a system call to the system call shim layer: `UK_SYSCALL_DEFINE` and `UK_SYSCALL_R_DEFINE`.
Agree with @dragosargint

2021-08-31 00:48 UTC, razvand commented on content/en/docs/sessions/07-syscall-shim/index.md
> +
Fully agree. Let them manually call system calls in a simple application using all the possible ways. They can do that with a simple call such as time: library call, system call, using `UK_SYSCALL_...`.

An additional task is for them to iterate through all system call (`0` to `__NR_syscall_max` - whatever this is) and see which are currently supported and which not in Unikraft.

2021-08-31 00:50 UTC, razvand requested changes
I did a review commit. I also added my comments to @dragosargint 's comments.

I think it really makes sense for them to directly use the syscall shim in a native application, just to get a hang of how things are going. This is useful both for understanding the syscall shim and the exposed interface and, for future reference, how you would test a correct system call implementation.

2021-08-31 10:33 UTC, danield20 commented
I have added a `System Calls` section, a new task as well as resolved changes that were suggested. Please, take a look.

2021-08-31 13:14 UTC, razvand approved these changes
All OK.

2021-08-31 13:14 UTC, merged