Add session contents for 03: Benchmarking and Debugging
unikraft/summer-of-code-2021 pull request #7
Opened 2021-08-18 23:25 UTC by gabrielmocanu

WIP

Signed-off-by: Viorel-Gabriel MOCANU (94548) <viorel.mocanu@stud.acs.upb.ro>

2021-08-20 18:56 UTC, razvand requested changes
Focus on using `kraft` as much as possible. `kraft` should be the default way to configure, build, run and debug Unikraft instances.

2021-08-20 18:56 UTC, razvand commented on content/en/docs/sessions/03-benchmarking-and-debugging/index.md
> +At this stage, you should be familiar with the steps of configuring, building and running any application within Unikraft and know the main parts of the architecture.
There should be a summary of commands on using `kraft` and `make` to configure, build and run Unikraft images.

2021-08-20 18:56 UTC, razvand commented on content/en/docs/sessions/03-benchmarking-and-debugging/index.md
> +```properties
What is `properties`?

2021-08-20 18:56 UTC, razvand commented on content/en/docs/sessions/03-benchmarking-and-debugging/index.md
> +qemu-system-x86_64 -s -S -cpu host -enable-kvm -m 128 -nodefaults -no-acpi -display none -serial stdio -device isa-debug-exit -kernel build/app-helloworld_kvm-x86_64.dbg -append verbose
We should be primarily using `kraft` for this. `kraft` is the main tool we want to use.

2021-08-20 18:56 UTC, razvand commented on content/en/docs/sessions/03-benchmarking-and-debugging/index.md
> +You can now run `continue` and debug as you would normally.
Add script / scripts to start in debugging mode and to attach with debugging configuration done.

2021-08-20 18:56 UTC, razvand commented on content/en/docs/sessions/03-benchmarking-and-debugging/index.md
> +## Tracepoints
First detail what the purpose is. Start with why. Then get to tracepoints as a means to that end. Ideally you can make a comparison to some other existing mechanism (maybe kprobes in Linux, or ftrace).

2021-08-20 18:56 UTC, razvand commented on content/en/docs/sessions/03-benchmarking-and-debugging/index.md
> +## Uniprof
Uniprof should only be minimally presented since we don't yet have KVM support.

2021-08-21 15:05 UTC, razvanvirtan commented on content/en/docs/sessions/03-benchmarking-and-debugging/index.md
> +### Creating Tracepoints
Maybe moving this section before `Read tracing data` would be more helpful? (I'm thinking that it would be the order of the steps made by the participants while solving tasks: configure, write code, test)

2021-08-21 15:05 UTC, razvanvirtan commented on content/en/docs/sessions/03-benchmarking-and-debugging/index.md
> +(gdb) uk trace
I think listing an output example would be nice, eventually the output generated by the example tracepoint from `Creating Tracepoints`.

2021-08-23 13:27 UTC, skuenzer commented on content/en/docs/sessions/03-benchmarking-and-debugging/index.md
> +qemu-system-x86_64 -s -S -cpu host -enable-kvm -m 128 -nodefaults -no-acpi -display none -serial stdio -device isa-debug-exit -kernel build/app-helloworld_kvm-x86_64.dbg -append verbose
Can kraft actually open you a debugger enpoint. I implemented somehting into `qemu-guest` to make it easy for debugging

2021-08-25 07:28 UTC, gabrielmocanu commented on content/en/docs/sessions/03-benchmarking-and-debugging/index.md
> +```properties
I tried to have a general highlights but it seems that docsy isn't supporting highlights in Markdown.
I remove them.

2021-08-25 07:29 UTC, gabrielmocanu commented on content/en/docs/sessions/03-benchmarking-and-debugging/index.md
> +qemu-system-x86_64 -s -S -cpu host -enable-kvm -m 128 -nodefaults -no-acpi -display none -serial stdio -device isa-debug-exit -kernel build/app-helloworld_kvm-x86_64.dbg -append verbose
I didn't find a solution with kraft to open a debugger endpoint.
I added an example of how to use qemu-guest to avoid using so many arguments with qemu-system.

2021-08-25 07:30 UTC, gabrielmocanu commented on content/en/docs/sessions/03-benchmarking-and-debugging/index.md
> +You can now run `continue` and debug as you would normally.
I added one script that is doing all this job.

2021-08-25 07:30 UTC, gabrielmocanu commented on content/en/docs/sessions/03-benchmarking-and-debugging/index.md
> +## Tracepoints
Done.

2021-08-25 07:31 UTC, gabrielmocanu commented on content/en/docs/sessions/03-benchmarking-and-debugging/index.md
> +
I put a short guide on how to run Xen.

2021-08-25 07:31 UTC, gabrielmocanu commented on content/en/docs/sessions/03-benchmarking-and-debugging/index.md
> +(gdb) uk trace
I added one tutorial about this and in that section it's an expected output.

2021-08-25 11:10 UTC, razvanvirtan commented on content/en/docs/sessions/03-benchmarking-and-debugging/index.md
> +After you have successfully run using kraft, try to make a Makefile for **Nginx** and run manually.
I think we should warn them about the required order of the libraries in `Makefile` (https://github.com/unikraft/lib-nginx)

2021-08-25 11:36 UTC, gabrielmocanu commented on content/en/docs/sessions/03-benchmarking-and-debugging/index.md
> +First try to run **Nginx** using kraft.
You are right. I was at a past commit where it looks like it was working. I'll wipe the kraft side.

2021-08-25 11:51 UTC, dragosargint commented on content/en/docs/sessions/03-benchmarking-and-debugging/index.md
> +
```suggestion
Also, if you are unfamiliar with X86_64 calling convention you can read more about it [here] (https://en.wikipedia.org/wiki/X86_calling_conventions)
```

2021-08-25 11:51 UTC, dragosargint commented on content/en/docs/sessions/03-benchmarking-and-debugging/index.md
> +Modify your `Echo-bach Server` application implemented in the [first](https://usoc21.unikraft.org/docs/sessions/01-baby-steps/#01-echo-back-server) session so that each time the server responds with
Shouldn't it be Echo-back?

2021-08-25 11:59 UTC, gabrielmocanu commented on content/en/docs/sessions/03-benchmarking-and-debugging/index.md
> +Modify your `Echo-bach Server` application implemented in the [first](https://usoc21.unikraft.org/docs/sessions/01-baby-steps/#01-echo-back-server) session so that each time the server responds with
Yes, I will change.

2021-08-25 13:42 UTC, razvand approved these changes
All OK.

2021-08-25 13:42 UTC, merged